apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
    - name: todoapp
      image: langrafka/todoapp:3.0.0
      ports:
        - containerPort: 8080
      env:
        - name: READINESS_DELAY
          value: "10" 
      readinessProbe:
        httpGet:
          path: /api/readiness/ # Використовуємо шлях, визначений у src/api/urls.py
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /api/liveness/ # Використовуємо шлях, визначений у src/api/urls.py
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 2
        failureThreshold: 3
